フォントファイルから出力される .php などの設定ファイルの出力先を、指定した$pathに設定できるようにする
satthi/TcpdfWrapper pull request #10
Opened 2019-09-05 11:16 UTC by tatsuroooK

2019-09-06 09:04 UTC, tatsuroooK reviewed
@satthi 
PRあげさせていただきます。
レビューをお願いします。

2019-09-06 09:04 UTC, tatsuroooK commented on src/TcpdfWrapper.php
> +        // build new font name for TCPDF compatibility
フォント設定キャッシュファイルが生成される際、そのファイル名に生成規則があるため、そのプログラムを参考にしています。
詳細は以下をご参考ください。
https://github.com/tecnickcom/TCPDF/blob/master/include/tcpdf_fonts.php#L79　から　https://github.com/tecnickcom/TCPDF/blob/master/include/tcpdf_fonts.php#L92　を参照ください。

2019-09-09 01:22 UTC, satthi requested changes
READMEも更新してください

2019-09-09 01:22 UTC, satthi commented on src/TcpdfWrapper.php
> +        if (!empty($this->fontSettingCacheFileOutDir)) {
このempty判定は「generateFontSettingCacheFilePath」の中で持てばいいのかなーって思ったんだけど

2019-09-09 01:22 UTC, satthi commented on src/TcpdfWrapper.php
> +        $font_name = strtolower($font_path_parts['filename']);
- コードの意味をもうちょいコメント書いてほしい
- コメントで参考箇所のURLを書いてほしい
- 変数はcamelizeで(ほかのコードに合わせてほしい

2019-09-09 01:22 UTC, satthi commented on src/TcpdfWrapper.php
> +    public function getFontSettingCacheFileOutDir()
これpublicな理由は？
外から読む必要性があるの？
＋
このメソッドそもそもいる？(処理の中で使うならともかく使ってないし

2019-09-09 05:41 UTC, tatsuroooK reviewed
修正しました！
ご確認をお願いします。

2019-09-09 05:41 UTC, tatsuroooK commented on src/TcpdfWrapper.php
> +        if (!empty($this->fontSettingCacheFileOutDir)) {
確かにそうでした、変更しました。

2019-09-09 05:41 UTC, tatsuroooK commented on src/TcpdfWrapper.php
> +        $font_name = strtolower($font_path_parts['filename']);
> コードの意味をもうちょいコメント書いてほしい
説明を追加しました！

> コメントで参考箇所のURLを書いてほしい
コード中に追記しました！

> 変数はcamelizeで(ほかのコードに合わせてほしい
統一しました。

2019-09-09 05:41 UTC, tatsuroooK commented on src/TcpdfWrapper.php
> +    public function getFontSettingCacheFileOutDir()
ゲッターとして用意していましたが、使用しないので削除しました。

2019-09-09 06:24 UTC, merged